# @package _global_

# Text dataset settings
text_dataset:
  dataset_path: "mideind/is_prototyping_corpus"
  max_length: 512
  max_entries: 10

# Image generation settings
image:
  width: 512
  height: 512
  dpi: 72
  background_color: "white"

# Font settings
font:
  path: "/System/Library/Fonts/Supplemental/Arial.ttf"
  size: 12
  color: "black"

# Text settings
text:
  vertical_alignment: "center" # top, middle, bottom
  horizontal_alignment: "left" # left, center, right

# Output settings
output:
  path: "isl_synthetic_ocr_output" # Directory to save dataset
  num_examples: 1000 # Number of examples to generate
  # push_to_hub: true # Whether to push dataset to Hugging Face Hub
  push_to_hub: false # Whether to push dataset to Hugging Face Hub
  hub_repo_id: "Sigurdur/isl_synthetic_ocr" # Hugging Face repo ID to push dataset
