[project]
name = "isl-synthetic-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "omegaconf>=2.3.0",
    "datasets>=4.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
